# Generated by Django 5.0.6 on 2024-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MCA', 'MCA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
