# Generated by Django 5.0.6 on 2024-05-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_actor_address_actor_course_actor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='gender',
        ),
    ]
